### ISSUE TITLE
Support for Lambda hosting

### ISSUE THREAD

**Issue by davidski** [scopely/slack-sns#8]
Hi!

I've been running this on Heroku for a while but am interested in moving the processing over to AWS Lambda. It looks like porting this over would be pretty straightforward. Before I go down the road of developing dual-support, would you be interested in a PR that supported hosting this bridge on both Heroku and Lambda?

**Comment by avram** [comment]
Yes, we'd be amenable to a PR that lets this run on Lambda as well.

Thanks for chipping in!

**Comment by davidski** [comment]
Closing out this old issue as I probably won't be picking up a dual Heroku/Lambda bridge for Slack in the near future.
